Add cloneNode missing argumen for Gecko <13.0 versions
FireFox till 13v (Gecko 13) is causing exception error:
---
Error: uncaught exception: [Exception... "Not enough arguments"
nsresult: "0x80570001 (NS_ERROR_XPC_NOT_ENOUGH_ARGS)"  location: "JS
frame ::
file:///tree.jquery.js
:: anonymous :: line 904"  data: no]
---
Fixed by adding (default: false) argument to cloneNode method. For new browsers cloneNode
methods 'deep' argument is optional, but for older it wasn't.

From: https://developer.mozilla.org/en-US/docs/Web/API/Node.cloneNode
This behavior has been changed in the latest spec, and if omitted, the
method will act as if the value of deep was false. Though It's still
optional, you should always provide the deep argument both for backward
and forward compatibility.